"""update playlist table

Revision ID: 05b7dae4bf6f
Revises: e24df46c5fea
Create Date: 2025-11-08 20:03:45.252738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b7dae4bf6f'
down_revision: Union[str, Sequence[str], None] = 'e24df46c5fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'playlists', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playlists', type_='foreignkey')
    op.drop_column('playlists', 'owner_id')
    # ### end Alembic commands ###
