"""album and track ratings

Revision ID: 80bcd91d0884
Revises: b269de091131
Create Date: 2025-12-15 23:16:37.249393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80bcd91d0884'
down_revision: Union[str, Sequence[str], None] = 'b269de091131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('album_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 10', name='check_rating_album'),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'album_id', name='uq_album_user_rating')
    )
    op.create_table('track_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 10', name='check_rating_range'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'track_id', name='uq_user_track_rating')
    )
    op.drop_constraint(op.f('users_list_hist_playlist_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'list_hist_playlist_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('list_hist_playlist_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_list_hist_playlist_id_fkey'), 'users', 'listening_history', ['list_hist_playlist_id'], ['id'])
    op.drop_table('track_ratings')
    op.drop_table('album_ratings')
    # ### end Alembic commands ###
