"""title

Revision ID: a8f27ed266b6
Revises: c87d8d261d41
Create Date: 2025-12-14 13:36:40.648629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f27ed266b6'
down_revision: Union[str, Sequence[str], None] = 'c87d8d261d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path'),
    sa.UniqueConstraint('track_id')
    )
    op.add_column('albums', sa.Column('cover_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'albums', 'titles', ['cover_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.drop_column('albums', 'cover_id')
    op.drop_table('titles')
    # ### end Alembic commands ###
