"""genres and genres track relationship

Revision ID: ae808fae5504
Revises: a8f27ed266b6
Create Date: 2025-12-14 16:20:53.122909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae808fae5504'
down_revision: Union[str, Sequence[str], None] = 'a8f27ed266b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_genres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('genre', sa.Enum('RAP', 'ROCK', 'CLASSIC', 'ELECTRO', 'SHANSON', name='genres'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_genres')
    # ### end Alembic commands ###
