"""not nullable title and norm class for playlisttrack table

Revision ID: e2090be74d6f
Revises: 8f56ec04d58b
Create Date: 2025-11-11 19:33:50.751878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2090be74d6f'
down_revision: Union[str, Sequence[str], None] = '8f56ec04d58b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_track', sa.Column('id', sa.UUID(), nullable=False))
    op.alter_column('playlist_track', 'track_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('playlist_track', 'playlist_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('playlists', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlists', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('playlist_track', 'playlist_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('playlist_track', 'track_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('playlist_track', 'id')
    # ### end Alembic commands ###
